FROM gcr.io/google_containers/kube-controller-manager-amd64:
AFC、ISCS、BAS、PSD、ATS、FAS、CCTV、PIS

AFC 城市轨道交通自动售检票系统
ISCS 城市轨道交通综合监控系统
BAS 建筑设备自动化系统
PSD 
ATS 自动列车监控系统
FAS 火灾报警系
CCTV 闭路电视监控系统
PIS 乘客信息系统
v1.10.2
#MAINTAINER tony <hyujun@gmail.com>
